"""Emit a storyboard module from content data alone.

Two jobs. It is the floor under code generation -- when the repair budget runs
out, a job still produces a video rather than nothing -- and it is the
`safe-deterministic` template a user can choose on purpose.

It writes source rather than being imported directly because the whole pipeline
below it expects a module in `storyboards/` with the standard contract: the
renderer imports by name, `sfx.py` reads `SFX` off the module, and `make.sh`
reads `AUDIO` and `PHRASES`. Emitting a real module keeps that one path.

Scene boundaries are taken from the alignment at import time, not from the
script's intended timecodes, so the cuts land on the narration however the
delivery actually came out.
"""
from __future__ import annotations

from pprint import pformat

from app.models.content import ReelContent

TEMPLATE = '''\
# ---------------------------------------------------------------
# {slug}.py -- generated by ReelForge from content data.
# No hand-written or model-written drawing code. Every scene names a layout
# from the screen catalogue, and DATA carries it fully resolved: which text,
# which slice of the facts, at which coordinates. This module only draws.
# ---------------------------------------------------------------
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PIL import Image, ImageChops, ImageDraw

import kit, sbkit as S
from kit import W, H, MARGIN, f, m, clamp, lin, eo3, eo4, rgba, tw, text, wrap, hline
from sbkit import Theme, WHITE, enter, statcard, terminal, tile, endcard
from timing import Timing

NAME    = {slug!r}
AUDIO   = {audio!r}
PHRASES = {phrases!r}
TOTAL   = {total!r}
FPS     = 30

DATA = {data}


def _fit_mark(word, start=250, floor=64):
    """Largest wordmark size that stays inside the safe width.

    `sbkit.endcard` draws the wordmark centred at a fixed size, so a long name
    runs off both edges -- "Harness Open Source" at 250px is far wider than the
    frame. It accepts a size, so the size is measured rather than assumed.
    """
    avail = W - 2 * MARGIN
    size = start
    while size > floor and tw(word, f(size, "bold"), 0) > avail:
        size -= 6
    return size

#: Prepared screenshots live beside the storyboard, inside the job workspace,
#: so `os.path.abspath(__file__)` finds them the same way `build/` is found.
#: The safe area, which is what the fade is shaped around: outside it the
#: platform's own UI sits on top, so anything legible there is content the
#: viewer never sees.
SAFE_TOP, SAFE_BOTTOM, SAFE_SIDE = 150, 1600, 84

#: What the image is scaled to at the safe boundary. Derived rather than
#: guessed: a linear ramp that merely *starts* at the frame edge is still 83%
#: opaque by the boundary, which is exactly what the safe-area check reported.
#: The exponent below is solved so the ramp passes through this value there.
#:
#: Measured against a near-white screenshot, the worst case: 0.45 passes the
#: safe-area check and 0.6 does not, so this sits just inside the margin and
#: shows as much of the image as the rule allows.
EDGE_AT_SAFE = 0.42

#: A full-bleed image also takes a gradient over its lower third, starting well
#: above the safe boundary. Two reasons, and both are about the same band: the
#: platform draws its caption bar and action buttons there, so anything legible
#: is content the viewer never sees; and burned-in captions sit on top of it.
#: A gradient reads as deliberate where a hard fade reads as a black bar.
BOTTOM_SCRIM_TOP, BOTTOM_SCRIM_MAX = 1180, 0.82

#: A light overall dim under a full-bleed image, so the eyebrow pill and the
#: repo tag in the corner stay readable over a bright screenshot. Light-mode
#: screenshots are near-white, and chrome drawn in white over white is not
#: chrome anyone can see.
FULL_BLEED_DIM = 0.16

HERE_IMAGES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "images")

_T = Timing(NAME)
CH = _T.chunks()
CAPTIONS = DATA.get("captions", True)
WORDS = _T.words

TH = Theme(bg=tuple(DATA["theme"]["bg"]), accent=tuple(DATA["theme"]["accent"]),
           accent_hi=tuple(DATA["theme"]["accent_hi"]), pale=tuple(DATA["theme"]["pale"]),
           glow=tuple(DATA["theme"]["glow"]), support=tuple(DATA["theme"]["support"]))
TH.apply()
BASE = S.build_base(TH, seed=DATA["theme"]["seed"], bloom=DATA["theme"]["bloom"])
DATA["mark_size"] = _fit_mark(DATA["wordmark"])


def _fit_mono(text, size, avail, track=0):
    """Trim to fit a size sbkit will not let us change, on a word boundary.

    Dropping one character at a time fits, and reads as broken: the end card
    showed "Drone's successor adds SCM, Gitspac". Backing up to the last space
    costs a word and looks deliberate.
    """
    original = text
    while text and tw(text, m(size), track) > avail:
        text = text[:-1]
    if text == original:
        # it fits as written -- do not touch it. Backing off unconditionally
        # turned "docker run -d" into "docker run", which is a different
        # command, and a command on screen has to be the one that works.
        return text
    head, space, _tail = text.rpartition(" ")
    if space and len(head) > len(text) * 0.5:
        text = head
    return text.rstrip(" ,.;:-")


# endcard draws these at fixed sizes, so they are trimmed rather than shrunk
DATA["endcard_sub"] = _fit_mono(DATA["endcard_sub"], 38, W - 2 * MARGIN, 3)
DATA["url"] = _fit_mono(DATA["url"], 40, W - 2 * MARGIN)
DATA["url2"] = _fit_mono(DATA["url2"], 34, W - 2 * MARGIN)


#: Spans and screens are resolved by app/render/screens.py at build time, where
#: the alignment and the content are both in hand. Doing it here would mean the
#: module needed the catalogue, the content and the picker -- and the reason
#: this renderer exists is that it never fails, which argues for less logic in
#: the executed module, not more.
SC = [(scr["id"], scr["start"], scr["end"]) for scr in DATA["screens"]]
CUTS = [start for _, start, _ in SC[1:]]


def screen_at(t):
    for screen in DATA["screens"]:
        if screen["start"] <= t < screen["end"]:
            return screen
    return DATA["screens"][-1]


def _fit(txt, size, weight="bold", avail=None):
    """Largest size at or below `size` whose text fits the safe width.

    The fallback has to survive whatever the content stage produced. Drawing at
    a fixed size meant a long hook line ran off both edges and tripped the
    safe-area check -- which failed the one storyboard that is supposed to be
    unfailable.
    """
    avail = avail if avail is not None else W - 2 * MARGIN
    step = size
    while step > 24:
        font = f(step, weight)
        if tw(txt, font, 0) <= avail:
            return font
        step -= 4
    return f(24, weight)


def _headline(ov, d, t, t0, lines, y=560, size=86, sub=None):
    fonts = [_fit(line, size) for line in lines]
    heights = [fnt.size + 16 for fnt in fonts]
    for row, (line, font) in enumerate(zip(lines, fonts)):
        k, dy = enter(t, t0 + row * 0.16, 0.36, 30)
        if k <= 0:
            continue
        text(d, (W // 2, y + sum(heights[:row]) + dy), line, font, WHITE, k, 0, "mt")
    if sub:
        k, dy = enter(t, t0 + 0.20 + 0.16 * len(lines), 0.36, 22)
        text(d, (W // 2, y + sum(heights) + 40 + dy), sub,
             _fit(sub, 38, "med"), TH.pale, k, 0, "mt")


def sl_headline(ov, d, t, t0, o):
    _headline(ov, d, t, t0 + o.get("delay", 0.12), o["lines"],
              y=o.get("y", 520), size=o.get("size", 84), sub=o.get("sub"))


def sl_statcards(ov, d, t, t0, o):
    stats = o["stats"][:3]
    if not stats:
        return
    box_w = (W - 2 * MARGIN - 24 * (len(stats) - 1)) // len(stats)
    height = o.get("height", 210)
    for i, (value, label) in enumerate(stats):
        x0 = MARGIN + i * (box_w + 24)
        statcard(ov, d, (x0, o["y"], x0 + box_w, o["y"] + height),
                 value, label, t, t0 + 0.20 + i * 0.14, TH)


def sl_factlist(ov, d, t, t0, o):
    for row, (label, value) in enumerate(o["rows"]):
        k, dy = enter(t, t0 + o.get("delay", 0.7) + row * 0.13, 0.34, 20)
        if k <= 0:
            continue
        y = o["y"] + row * 78 + dy
        text(d, (MARGIN, y), label.upper(), m(24), TH.muted, k * 0.9, 1, "lt")
        text(d, (MARGIN, y + 30), value, _fit(value, 34, "med"), WHITE, k, 0, "lt")


def sl_terminal(ov, d, t, t0, o):
    lines = [(cmd, t0 + 0.45 + i * 1.1, t0 + 1.35 + i * 1.1)
             for i, cmd in enumerate(o["lines"][:3])]
    height = o.get("height", 90 + 62 * max(len(lines), 1))
    terminal(ov, d, (MARGIN, o["y"], W - MARGIN, o["y"] + height),
             lines, t, TH, title=o.get("title", ""))


def sl_tiles(ov, d, t, t0, o):
    # value first, label under it. `tile` draws its main text at 34px and its
    # sub at 24px in the dim colour, so putting the label on top made the
    # licence and the repo name -- the part worth reading -- unreadable.
    for row, (label, value) in enumerate(o["rows"]):
        k, dy = enter(t, t0 + o.get("delay", 0.9) + row * 0.16, 0.34, 20)
        if k <= 0:
            continue
        y = o["y"] + row * 84 + dy
        tile(ov, d, (MARGIN, y, W - MARGIN, y + 74), value, min(1.0, k),
             TH, k=k, sub=label.upper(), mono=o.get("mono", True))


def sl_counter(ov, d, t, t0, o):
    # a number that ticks up reads as a beat; one that is simply drawn does not
    S.counter(ov, d, (W // 2, o["y"]), o["target"], t, t0 + o.get("delay", 0.25),
              TH, size=o.get("size", 132), label=o.get("label"))


def sl_quote(ov, d, t, t0, o):
    lines = o["lines"]
    for row, line in enumerate(lines):
        k, dy = enter(t, t0 + 0.15 + row * 0.18, 0.40, 26)
        if k <= 0:
            continue
        text(d, (W // 2, o["y"] + row * (o.get("size", 76) + 18) + dy), line,
             _fit(line, o.get("size", 76)), WHITE, k, 0, "mt")


_IMAGE_CACHE = {{}}


def _load_image(name):
    """Open a prepared screenshot once per process.

    Each parallel chunk is its own process, so this caches within a chunk and
    the file is read a handful of times rather than once per frame.
    """
    if name not in _IMAGE_CACHE:
        path = os.path.join(HERE_IMAGES, name)
        _IMAGE_CACHE[name] = Image.open(path).convert("RGBA")
    return _IMAGE_CACHE[name]


def _rounded(img, radius):
    """Round an image's corners, so it sits on the ground like every card."""
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, img.width - 1, img.height - 1), radius=radius, fill=255)
    out = img.copy()
    out.putalpha(mask)
    return out


_EDGE_FADE = [None]


def _edge_fade():
    """A mask that fades a full-bleed image into the ground at every edge.

    The safe-area check measures legibility, not difference, because these
    storyboards use full-bleed decorative layers by design. A bright screenshot
    run edge to edge is legible in the corners -- which is where the platform's
    own UI sits, so a viewer never reads it and the check is right to say so.

    Fading the edges makes the frame honestly safe rather than silencing the
    check: the centre stays sharp and carries the screenshot, the outer band
    becomes ground, and burned-in captions over the lower third stay readable.
    """
    if _EDGE_FADE[0] is None:
        import math as _math

        import numpy as _np

        def ramp(length, lead, tail):
            """Fade in over `lead` and out over `tail`, passing through
            EDGE_AT_SAFE where the safe area begins."""
            out = _np.ones(length)
            for span, target in ((lead, "lead"), (tail, "tail")):
                if not span:
                    continue
                # solve p so (safe/span)**p == EDGE_AT_SAFE
                safe = min(max(span * 0.5, 1.0), span - 1.0)
                power = _math.log(EDGE_AT_SAFE) / _math.log(safe / span)
                curve = _np.linspace(0.0, 1.0, span) ** power
                if target == "lead":
                    out[:span] = curve
                else:
                    out[length - span:] = curve[::-1]
            return out

        # twice the safe margin, so the ramp is well under way by the boundary
        columns = ramp(W, SAFE_SIDE * 2, SAFE_SIDE * 2)
        rows = ramp(H, SAFE_TOP * 2, (H - SAFE_BOTTOM) * 2)
        field = _np.outer(rows, columns) * 255.0
        _EDGE_FADE[0] = Image.fromarray(field.astype("uint8"), "L")
    return _EDGE_FADE[0]


_SCRIM_CACHE = {{}}


_SIDE_FADE = {{}}


def _side_fade(height):
    """Fade a full-width panel's left and right bands into the ground.

    A panel that spans the frame necessarily reaches x 0 and x 1080, outside the
    safe area -- the same thing full-bleed does, for the same reason, and the
    safe-area check is right to flag it either way. Fading the sides makes the
    band under the platform UI decorative instead of information nobody sees.
    """
    if height not in _SIDE_FADE:
        import math as _math

        import numpy as _np

        span = SAFE_SIDE * 2
        power = _math.log(EDGE_AT_SAFE) / _math.log(0.5)
        curve = _np.linspace(0.0, 1.0, span) ** power
        columns = _np.ones(W)
        columns[:span] = curve
        columns[W - span:] = curve[::-1]
        field = _np.tile(columns, (height, 1)) * 255.0
        _SIDE_FADE[height] = Image.fromarray(field.astype("uint8"), "L")
    return _SIDE_FADE[height]


def _bottom_scrim(k):
    """A gradient over the lower band of a full-bleed image."""
    key = round(k, 2)
    if key not in _SCRIM_CACHE:
        import numpy as _np

        depth = H - BOTTOM_SCRIM_TOP
        ramp = _np.zeros(H)
        ramp[BOTTOM_SCRIM_TOP:] = (
            _np.linspace(0.0, 1.0, depth) ** 1.4) * BOTTOM_SCRIM_MAX * key
        layer = _np.zeros((H, W, 4), dtype="uint8")
        layer[:, :, 3] = (ramp[:, None] * 255).astype("uint8")
        _SCRIM_CACHE[key] = Image.fromarray(layer, "RGBA")
    return _SCRIM_CACHE[key]


def sl_image(ov, d, t, t0, o):
    """A screenshot: the one thing on screen the pipeline did not draw itself.

    `panel` keeps the whole image inside a card on the reel's own ground, which
    is how the shipped storyboards present a terminal. `full` fills the frame
    and takes a scrim, because burned-in captions sit over the lower third and a
    bright screenshot underneath makes them unreadable.
    """
    k, dy = enter(t, t0 + o.get("delay", 0.10), 0.40, 26)
    if k <= 0:
        return
    img = _load_image(o["file"])

    if o.get("fit") == "full":
        # into ov, not via d.rectangle: ImageDraw replaces pixels rather than
        # blending, and would erase the layer (gotcha 1)
        faded = img.copy()
        alpha = ImageChops.multiply(img.getchannel("A"), _edge_fade())
        faded.putalpha(alpha.point(lambda a: int(a * k)))
        ov.alpha_composite(faded, (0, 0))
        S.scrim(ov, FULL_BLEED_DIM * k)
        ov.alpha_composite(_bottom_scrim(k))
        if o.get("label"):
            text(d, (W // 2, 1300 if CAPTIONS else 1460), o["label"],
                 _fit(o["label"], 56, "bold"), WHITE, k, 2, "mb")
        return

    # A panel spans the full frame width, so it is rounded only where it does
    # not meet an edge -- a rounded corner against the frame edge reads as a
    # mistake rather than a card.
    card = _rounded(img, 22) if img.width < W else img.copy()
    y = int(o.get("y", 430) + dy)
    x = (W - card.width) // 2
    if card.width < W:
        d.rounded_rectangle((x - 2, y - 2, x + card.width + 1, y + card.height + 1),
                            radius=24, outline=rgba(TH.border, 0.95 * k), width=2)
    else:
        d.line((0, y - 1, W, y - 1), fill=rgba(TH.border, 0.8 * k), width=2)
        d.line((0, y + card.height, W, y + card.height),
               fill=rgba(TH.border, 0.8 * k), width=2)
    faded = card.copy()
    alpha = card.getchannel("A")
    if card.width >= W:
        alpha = ImageChops.multiply(alpha, _side_fade(card.height))
    faded.putalpha(alpha.point(lambda a: int(a * k)))
    ov.alpha_composite(faded, (x, y))

    caption = o.get("caption") or o.get("label")
    if caption:
        # above the image, never below: a panel at the bottom of the band ends
        # where the burned-in captions begin, and two lines of text in the same
        # place means neither can be read
        text(d, (W // 2, y - 34), caption,
             _fit(caption, 30 if o.get("caption") else 40, "med" if o.get("caption") else "bold"),
             TH.muted if o.get("caption") else WHITE, k, 0, "mb")


def sl_scroll(ov, d, t, t0, o):
    """The repo page, panned top to bottom inside the panel band.

    Bloom burns captions in, so this pans within the band rather than full
    bleed -- caption text over a scrolling README is unreadable, and the band
    is exactly the room a panel already has.
    """
    try:
        img = _load_image(o.get("file", ""))
    except Exception:
        return
    if img.width != W:
        img = img.resize((W, int(img.height * W / img.width)), Image.LANCZOS)
    top = 380
    band = min(1060, (1440 if DATA.get("captions", True) else 1580) - top)
    dur = float(o.get("dur", 8.0))
    k = eo3(lin(t, t0, t0 + 0.34))
    if k <= 0.01:
        return
    # Distance is speed x time, not "the whole page however tall it is".
    # Fitting a 8768px page into a 6s scene meant ~1600 px/s and read as a
    # blur; showing the repo is the point, not reaching its footer.
    p = clamp((t - t0 - 0.34) / max(dur - 0.34, 0.01))
    hold, speed = 0.12, float(o.get("speed", 300))
    travel = min(max(0, img.height - band), speed * (dur - 0.34) * (1.0 - hold))
    q = clamp((p - hold) / max(1.0 - hold, 0.05))
    q = q * q * (3.0 - 2.0 * q)
    y = int(q * travel)
    crop = _rounded(img.crop((0, y, W, min(y + band, img.height))).convert("RGBA"), 22)
    # a README is a white page and this panel spans the frame, so the side
    # bands take the same fade the full-width screenshots take
    crop.putalpha(ImageChops.multiply(crop.getchannel("A"), _side_fade(crop.height)))
    ov.alpha_composite(crop, (0, top))
    label = o.get("label") or DATA["tag"]
    if label:
        text(d, (W // 2, top - 30), label, m(30, "bold"), TH.accent_hi, k, 2, "mb")



# ---- generated clips -------------------------------------------------------
# A clip is a directory of JPEG frames at the reel's own size and frame rate,
# extracted once by the visuals stage, so drawing it is pasting frame n --
# exactly what the repo scroll does with one tall PNG, for the same reason:
# the renderer is a PIL frame pump and cannot decode video.
_CLIP_CACHE = {{}}
_CLIP_ORDER = []


def _clip_frame(dirname, index):
    """One frame, behind a small LRU: a chunk process holds a handful of
    decoded frames rather than a whole clip."""
    key = (dirname, index)
    if key in _CLIP_CACHE:
        return _CLIP_CACHE[key]
    path = os.path.join(HERE_IMAGES, dirname, "%05d.jpg" % (index + 1))
    try:
        img = Image.open(path).convert("RGBA")
    except Exception:
        img = None
    _CLIP_CACHE[key] = img
    _CLIP_ORDER.append(key)
    while len(_CLIP_ORDER) > 12:
        _CLIP_CACHE.pop(_CLIP_ORDER.pop(0), None)
    return img


def _clip_index(t, t0, fps, n):
    """Ping-pong through the frames, so a scene longer than its clip turns
    around instead of jumping back to the first frame."""
    if n <= 1:
        return 0
    i = int(max(0.0, t - t0) * fps)
    cycle = 2 * (n - 1)
    i %= cycle
    return i if i < n else cycle - i


def _band_scrim(colour, height, solid, fade, flip=False):
    """Solid `colour` for `solid` rows then a fade over `fade` rows -- the
    shape the slab scroll uses so chrome stays legible over a picture."""
    key = ("scrim", tuple(colour), height, solid, fade, flip)
    if key not in _CLIP_CACHE:
        layer = Image.new("RGBA", (W, height), (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        for row in range(height):
            r = height - 1 - row if flip else row
            a = 1.0 if r < solid else max(0.0, 1.0 - (r - solid) / max(1, fade))
            ld.line((0, row, W, row), fill=rgba(colour, a))
        _CLIP_CACHE[key] = layer
    return _CLIP_CACHE[key]


def sl_clip(ov, d, t, t0, o):
    """A generated clip, full bleed under the eyebrow and the captions.

    Treated like a `full` screenshot: edge fade, the same dim scrim, the
    bottom scrim so burned-in captions stay readable over moving picture.
    """
    k = eo3(lin(t, t0, t0 + 0.40))
    if k <= 0.01:
        return
    img = _clip_frame(o["dir"], _clip_index(t, t0, int(o.get("fps", 30)), int(o.get("frames", 1))))
    if img is None:
        return
    faded = img.copy()
    alpha = ImageChops.multiply(img.getchannel("A"), _edge_fade())
    faded.putalpha(alpha.point(lambda a: int(a * k)))
    ov.alpha_composite(faded, (0, 0))
    S.scrim(ov, FULL_BLEED_DIM * k)
    ov.alpha_composite(_bottom_scrim(k))
    # the scene's title over the bottom scrim, so a dark clip still carries
    # a line of text and the screen is never just a picture under an eyebrow
    if o.get("label"):
        text(d, (W // 2, 1300 if CAPTIONS else 1460), o["label"],
             _fit(o["label"], 48, "bold"), WHITE, k, 2, "mb")



def _fit_line(value, face, track, budget, url=False):
    """The end cards draw their lines at fixed sizes; the strings bend instead.

    A URL loses its host first -- the path is the identity, the host is
    boilerplate -- and anything still too wide is ellipsis-trimmed. Measured
    with the same face and tracking the card will draw with, because whether
    a line fits depends on which letters it uses."""
    if not value:
        return value
    out = str(value)
    if tw(out, face, track) <= budget:
        return out
    if url and "/" in out:
        out = out.split("/", 1)[1]
        if tw(out, face, track) <= budget:
            return out
    while out and tw(out + "\\u2026", face, track) > budget:
        out = out[:-1]
    return (out.rstrip() + "\\u2026") if out else str(value)[:8]


def sl_endcard(ov, d, t, t0, o):
    # start the entrance before the cut, so the frame just after the cut is
    # already substantially drawn rather than a near-empty fade-up
    budget = W - 2 * MARGIN
    endcard(ov, d, t, t0 - 0.30, TH, DATA["wordmark"],
            _fit_line(DATA["endcard_sub"], m(38), 3, budget),
            _fit_line(DATA["url"], m(40, "bold"), 0, budget, url=True),
            _fit_line(DATA["url2"], m(34), 0, budget, url=True),
            _fit_line(DATA["cta"], f(40, "bold"), 4, budget - 112),
            mark_size=DATA["mark_size"])


SLOTS = {{
    "headline": sl_headline, "statcards": sl_statcards, "factlist": sl_factlist,
    "terminal": sl_terminal, "tiles": sl_tiles, "counter": sl_counter,
    "quote": sl_quote, "image": sl_image, "scroll": sl_scroll,
    "clip": sl_clip, "endcard": sl_endcard,
}}


#: Entrances begin before the cut they belong to. A screen is only drawn inside
#: its own span, so starting the animation early means it is already part-way in
#: at the cut instead of fading up from nothing -- which is what "the hook is
#: fully on screen at frame 0" means, applied to every cut rather than just the
#: first. Without it every cut is followed by ~0.3s of near-empty frame, and the
#: smoke check is right to call that bare.
PRE_ROLL = 0.34


def draw_screen(ov, d, t, t0, screen):
    # the opener has no cut to land on, so it starts fully arrived
    t0 = t0 - (PRE_ROLL if t0 > 0.01 else 1.0)
    if screen.get("eyebrow"):
        S.eyebrow(ov, d, screen["eyebrow"], t, t0, TH)
    for slot in screen["slots"]:
        SLOTS[slot["kind"]](ov, d, t, t0, slot)


def frame(t):
    base = BASE.copy()
    ov = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(ov)
    screen = screen_at(t)
    draw_screen(ov, d, t, screen["start"], screen)

    S.chrome(base, d, t, TH, TOTAL, DATA["tag"])
    S.cut_sweep(ov, d, t, CUTS, TH)
    # the end card owns the lower third, so captions stop before it
    if CAPTIONS and not screen.get("is_end"):
        S.captions(ov, d, t, CH, TH)
    base.alpha_composite(ov)
    return base


SFX = (
    [{{"t": c - 0.30, "kind": "swish", "amp": 0.20, "dur": 0.30}} for c in CUTS]
    + [{{"t": c, "kind": "thump", "amp": 0.28, "dur": 0.52, "freq": 48.0}} for c in CUTS]
    + [{{"t": SC[-1][1], "kind": "sweep", "amp": 0.16, "dur": 1.6}}]
)
'''


SLAB_TEMPLATE = '''\\
# ---------------------------------------------------------------
# {slug}.py -- generated by ReelForge from content data, on the SLAB template.
# Same contract and the same resolved DATA as the default renderer; what
# differs is the language. Full-bleed colour fields, one idea per screen, type
# colour derived from the field so a frame cannot come out illegible.
# ---------------------------------------------------------------
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PIL import Image, ImageChops, ImageDraw

import kit, slab as S
from kit import W, H, f, m, clamp, lin, eo3, eo4, rgba, tw, text, wrap
from slab import Theme, CX, CR, ink_for
from timing import Timing

NAME     = {slug!r}
AUDIO    = {audio!r}
PHRASES  = {phrases!r}
TOTAL    = {total}
FPS      = 30
CAPTIONS = False          # Slab has no caption plate; see DEVELOPMENT.md
#: The rail at y 128 is Slab's one deliberate mark inside the top margin --
#: persistent chrome, not stray content. Declared so the smoke check's band
#: test leaves those rows to the design.
SAFE_CLAIMED = ((120, 148),)

DATA = {data}

_T = Timing(NAME)
TH = Theme(fields=[tuple(c) for c in DATA["theme"]["fields"]],
           mark=tuple(DATA["theme"]["accent"]))
TH.apply()


def _fit_mark(word, start=170, floor=62):
    """Shrink the end-card wordmark until it fits Slab's content width."""
    size = start
    while size > floor and tw(word, f(size, "bold"), -1) > (CR - CX):
        size -= 6
    return size


DATA["mark_size"] = _fit_mark(DATA["wordmark"])

SC = [(s["id"], s["start"], s["end"]) for s in DATA["screens"]]
CUTS = [a for _, a, _ in SC[1:]]


def screen_at(t):
    for i, s in enumerate(DATA["screens"]):
        if s["start"] <= t < s["end"]:
            return i, s
    return len(DATA["screens"]) - 1, DATA["screens"][-1]


def _fit_lines(lines, size, avail, floor=48):
    while size > floor and any(tw(x, f(size, "bold"), -1) > avail for x in lines):
        size -= 4
    return size


# ---- slots ------------------------------------------------------------
def sl_headline(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x][:3]
    if not lines:
        return
    size = _fit_lines(lines, int(o.get("size", 112)), CR - CX)
    S.statement(ov, d, lines, t, t0, TH, i, y=int(o.get("y", 400)), size=size)


def _pairs(o, limit=3):
    rows = []
    for row in (o.get("rows") or [])[:limit]:
        if isinstance(row, (list, tuple)):
            rows.append((str(row[0]), str(row[1]) if len(row) > 1 else None))
        else:
            rows.append((str(row), None))
    return rows



def _fit_row_value(label, value, avail, lsize, vsize, mono=True):
    """The row draws its label from the left and its value against the right
    edge; nothing else keeps them apart. Trim the value to the room the label
    leaves, ellipsis and all, and drop it entirely when there is no room --
    a missing value reads better than two strings through each other."""
    if not value:
        return value
    room = avail - tw(str(label), f(lsize, "bold"), 1) - 28
    if room < 60:
        return None
    face = (m if mono else f)(vsize)
    out = str(value)
    if tw(out, face, 0) <= room:
        return out
    while out and tw(out + "\\u2026", face, 0) > room:
        out = out[:-1]
    return (out.rstrip() + "\\u2026") if out else None


def sl_factlist(ov, d, t, t0, o, i):
    rows = _pairs(o, int(o.get("limit", 3)))
    rows = [(l, _fit_row_value(l, v, 996 - CX, 42, 32)) for l, v in rows]
    if rows:
        S.rows(ov, d, rows, t, t0, TH, i, y=int(o.get("y", 900)), h=120, lsize=42,
               vsize=32, lit=[1.0] * len(rows))


def sl_statcards(ov, d, t, t0, o, i):
    # _resolve emits "stats" here, not "rows"
    rows = [(str(l), str(v)) for v, l in (o.get("stats") or [])][:3]
    rows = [(l, _fit_row_value(l, v, 996 - CX, 42, 34)) for l, v in rows]
    if rows:
        S.rows(ov, d, rows, t, t0, TH, i, y=int(o.get("y", 900)), h=120,
               lsize=42, vsize=34, lit=[1.0] * len(rows))


def sl_tiles(ov, d, t, t0, o, i):
    rows = _pairs(o, int(o.get("limit", 4)))
    if rows:
        S.rows(ov, d, rows, t, t0, TH, i, y=int(o.get("y", 900)), h=108, gap=8,
               lsize=40, vsize=28, lit=[1.0] * len(rows))


def sl_terminal(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x]
    if not lines:
        return
    y = int(o.get("y", 980))
    # a lone command on a full-bleed field is too little -- the title that
    # _resolve already supplies becomes the statement above it
    title = str(o.get("title") or "").strip()
    if title:
        S.statement(ov, d, [title], t, t0, TH, i, y=y - 360, size=104)
    S.command(ov, d, lines[0], t, t0 + 0.12, TH, i, y)
    for n, extra in enumerate(lines[1:3]):
        S.command(ov, d, extra, t, t0 + 0.12 + 0.14 * (n + 1), TH, i,
                  y + 118 * (n + 1))


def sl_counter(ov, d, t, t0, o, i):
    # _resolve emits "target"/"label"; Slab counts up to it like Bloom does
    target = o.get("target")
    if target is None:
        return
    S.counter(ov, d, t, t0, TH, i, int(o.get("y", 940)), int(target),
              label=str(o.get("label") or "").upper(),
              vsize=int(o.get("size", 180)))


def sl_quote(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x][:3]
    if lines:
        S.band(ov, d, lines, t, t0, TH, i, y=int(o.get("y", 900)), size=52,
               attrib=o.get("attrib") or None)


def sl_image(ov, d, t, t0, o, i):
    """A picture the pipeline did not draw: an uploaded screenshot, or a
    generated still.

    It is pasted at the full frame width, which puts it under the platform's
    action-button column, so it takes the same side scrims the repo scroll
    takes. A photograph often survives without them; a screenshot never does
    -- it is bright, rectangular, high-contrast interface right out to its
    border, which is exactly what the safe-area check counts.
    """
    name = o.get("file")
    if not name:
        return
    path = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "images", name)
    if not os.path.exists(path):
        return
    try:
        img = Image.open(path).convert("RGB")
    except Exception:
        return
    y = int(o.get("y", 560))
    hgt = min(int(img.height * W / img.width), 1500 - y)
    if hgt < 120:
        return
    img = img.resize((W, int(img.height * W / img.width)), Image.LANCZOS)
    k = S.rk(t, t0, 0.46)
    if k <= 0.01:
        return
    S.rise(ov, lambda L, D, im=img.crop((0, 0, W, hgt)), yy=y:
           L.paste(im, (0, yy)), (0, y, W, y + hgt), k)
    _side_scrims(ov, TH.field(i))
    if o.get("label"):
        S.chip(ov, d, (CX, y - 52), o["label"], t, t0 + 0.10, TH, i, size=34)


def _side_scrims(ov, fill):
    """Field colour over the outer columns, solid at the frame edge and gone
    by the end of the margin -- the pan is a white page and full bleed, and
    the platform UI sits exactly there."""
    key = ("sidescrim", tuple(fill))
    if key not in _CLIP_CACHE:
        band = Image.new("RGBA", (150, H), (0, 0, 0, 0))
        bd = ImageDraw.Draw(band)
        for x in range(150):
            # still ~55% cover AT the safe edge, gone by x 150: a fade that
            # reaches zero at x 84 leaves the outer checked columns bare,
            # and a white page there is exactly what trips the band test
            a = max(0.0, 1.0 - (x / 150.0) ** 1.4)
            bd.line((x, 0, x, H), fill=rgba(fill, a))
        _CLIP_CACHE[key] = band
    band = _CLIP_CACHE[key]
    ov.alpha_composite(band, (0, 0))
    ov.alpha_composite(band.transpose(Image.FLIP_LEFT_RIGHT), (W - band.width, 0))


def sl_scroll(ov, d, t, t0, o, i):
    """The repo page, panned top to bottom under the narration."""
    path = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "images", o.get("file", ""))
    S.scroll(ov, d, t, t0 + 0.30, float(o.get("dur", 8.0)) - 0.30, TH, i, path,
             speed=float(o.get("speed", S.SCROLL_SPEED)),
             label=o.get("label") or DATA["tag"])
    _side_scrims(ov, TH.field(i))



# ---- generated clips -------------------------------------------------------
# A clip is a directory of JPEG frames at the reel's own size and frame rate,
# extracted once by the visuals stage, so drawing it is pasting frame n --
# exactly what the repo scroll does with one tall PNG, for the same reason:
# the renderer is a PIL frame pump and cannot decode video.
_CLIP_CACHE = {{}}
_CLIP_ORDER = []


def _clip_frame(dirname, index):
    """One frame, behind a small LRU: a chunk process holds a handful of
    decoded frames rather than a whole clip."""
    key = (dirname, index)
    if key in _CLIP_CACHE:
        return _CLIP_CACHE[key]
    path = os.path.join(_HERE_IMAGES, dirname, "%05d.jpg" % (index + 1))
    try:
        img = Image.open(path).convert("RGBA")
    except Exception:
        img = None
    _CLIP_CACHE[key] = img
    _CLIP_ORDER.append(key)
    while len(_CLIP_ORDER) > 12:
        _CLIP_CACHE.pop(_CLIP_ORDER.pop(0), None)
    return img


def _clip_index(t, t0, fps, n):
    """Ping-pong through the frames, so a scene longer than its clip turns
    around instead of jumping back to the first frame."""
    if n <= 1:
        return 0
    i = int(max(0.0, t - t0) * fps)
    cycle = 2 * (n - 1)
    i %= cycle
    return i if i < n else cycle - i


def _band_scrim(colour, height, solid, fade, flip=False):
    """Solid `colour` for `solid` rows then a fade over `fade` rows -- the
    shape the slab scroll uses so chrome stays legible over a picture."""
    key = ("scrim", tuple(colour), height, solid, fade, flip)
    if key not in _CLIP_CACHE:
        layer = Image.new("RGBA", (W, height), (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        for row in range(height):
            r = height - 1 - row if flip else row
            a = 1.0 if r < solid else max(0.0, 1.0 - (r - solid) / max(1, fade))
            ld.line((0, row, W, row), fill=rgba(colour, a))
        _CLIP_CACHE[key] = layer
    return _CLIP_CACHE[key]

_HERE_IMAGES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "images")
_SIDE_MASK = [None]


def _side_mask():
    """Opaque across the safe width, fading to nothing at the frame edge."""
    if _SIDE_MASK[0] is None:
        mask = Image.new("L", (W, H), 255)
        md = ImageDraw.Draw(mask)
        edge = 84 + 36
        for x in range(edge):
            a = int(255 * (x / edge) ** 1.6)
            md.line((x, 0, x, H), fill=a)
            md.line((W - 1 - x, 0, W - 1 - x, H), fill=a)
        _SIDE_MASK[0] = mask
    return _SIDE_MASK[0]


def sl_clip(ov, d, t, t0, o, i):
    """Full bleed, with the slab scroll's scrims so the rail at y 128 and the
    footer at y 1524 sit on field colour rather than on the picture."""
    k = S.rk(t, t0, 0.40)
    if k <= 0.01:
        return
    img = _clip_frame(o["dir"], _clip_index(t, t0, int(o.get("fps", 30)), int(o.get("frames", 1))))
    if img is None:
        return
    layer = img.copy()
    # fade the sides into the field: the platform's UI sits in the outer
    # columns, and a bright picture there is content nobody can read
    alpha = ImageChops.multiply(layer.getchannel("A"), _side_mask())
    layer.putalpha(alpha.point(lambda a: int(a * k)))
    ov.alpha_composite(layer, (0, 0))
    fill = TH.field(i)
    ov.alpha_composite(_band_scrim(fill, 340, 176, 164), (0, 0))
    ov.alpha_composite(_band_scrim(fill, H - 1330, H - 1484, 154, flip=True), (0, 1330))
    if o.get("label"):
        S.chip(ov, d, (CX, 236), o["label"], t, t0 + 0.10, TH, i, size=32)



def _fit_line(value, face, track, budget, url=False):
    """The end cards draw their lines at fixed sizes; the strings bend instead.

    A URL loses its host first -- the path is the identity, the host is
    boilerplate -- and anything still too wide is ellipsis-trimmed. Measured
    with the same face and tracking the card will draw with, because whether
    a line fits depends on which letters it uses."""
    if not value:
        return value
    out = str(value)
    if tw(out, face, track) <= budget:
        return out
    if url and "/" in out:
        out = out.split("/", 1)[1]
        if tw(out, face, track) <= budget:
            return out
    while out and tw(out + "\\u2026", face, track) > budget:
        out = out[:-1]
    return (out.rstrip() + "\\u2026") if out else str(value)[:8]


def sl_endcard(ov, d, t, t0, o, i):
    budget = CR - CX
    S.endcard(ov, d, t, t0 - 0.30, TH, i, DATA["wordmark"],
              _fit_line(DATA["endcard_sub"], f(40, "med"), 0, budget),
              _fit_line(DATA["url"], m(36, "bold"), 0, budget, url=True),
              _fit_line(DATA["cta"], f(38, "bold"), 0, budget - 84),
              mark_size=DATA["mark_size"])


SLOTS = {{
    "headline": sl_headline, "statcards": sl_statcards, "factlist": sl_factlist,
    "terminal": sl_terminal, "tiles": sl_tiles, "counter": sl_counter,
    "quote": sl_quote, "image": sl_image, "scroll": sl_scroll,
    "clip": sl_clip, "endcard": sl_endcard,
}}

PRE_ROLL = 0.30


def frame(t):
    i, screen = screen_at(t)
    base = S.field_for(TH, i).copy()
    ov = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(ov)
    t0 = screen["start"] - (PRE_ROLL if screen["start"] > 0.01 else 1.0)
    for slot in screen["slots"]:
        SLOTS[slot["kind"]](ov, d, t, t0, slot, i)
    # cut BEFORE chrome: the band is opaque and would blank the rail
    S.cut(ov, d, t, CUTS, TH, lambda tt: screen_at(tt)[0])
    span = max(screen["end"] - screen["start"], 0.01)
    S.rail(ov, d, t, TH, i, len(DATA["screens"]), (t - screen["start"]) / span)
    S.footer(ov, d, TH, i, DATA["tag"], len(DATA["screens"]))
    base.alpha_composite(ov)
    return base


SFX = (
    [{{"t": c - 0.18, "kind": "paper", "amp": 0.14}} for c in CUTS]
    + [{{"t": c, "kind": "slam", "amp": 0.24, "dur": 0.24}} for c in CUTS]
    + [{{"t": SC[-1][1] - 0.20, "kind": "riser", "amp": 0.10}}]
)
'''


LEDGER_TEMPLATE = '''\\
# ---------------------------------------------------------------
# {slug}.py -- generated by ReelForge from content data, on the LEDGER
# template. Same contract and the same resolved DATA as the other two; what
# differs is the language: everything hangs off a vertical spine, hairline
# rules instead of cards, and a scene index that accumulates in the gutter.
# ---------------------------------------------------------------
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PIL import Image, ImageDraw

import kit, ledger as L
from kit import W, H, f, m, clamp, lin, eo3, eo4, rgba, tw, text, wrap
from ledger import Theme, WHITE, CX, RIGHT, STAGE_Y0, STAGE_Y1, right_edge
from timing import Timing

NAME     = {slug!r}
AUDIO    = {audio!r}
PHRASES  = {phrases!r}
TOTAL    = {total}
FPS      = 30

DATA = {data}
CAPTIONS = bool(DATA.get("captions", False))

_T = Timing(NAME)
CH = _T.chunks()
# ledger.Theme derives its own glow from `faint`; it takes no glow argument
TH = Theme(bg=tuple(DATA["theme"]["bg"]), accent=tuple(DATA["theme"]["accent"]),
           accent_hi=tuple(DATA["theme"]["accent_hi"]),
           pale=tuple(DATA["theme"]["pale"]),
           support=tuple(DATA["theme"]["support"]))
TH.apply()
BASE = L.build_ground(TH, seed=DATA["theme"]["seed"])

SC = [(s["id"], s["start"], s["end"]) for s in DATA["screens"]]
CUTS = [a for _, a, _ in SC[1:]]


def _fit_mark(word, start=150, floor=56):
    size = start
    while size > floor and tw(word, f(size, "bold"), 0) > (RIGHT - CX):
        size -= 6
    return size


DATA["mark_size"] = _fit_mark(DATA["wordmark"])


def screen_at(t):
    for i, s in enumerate(DATA["screens"]):
        if s["start"] <= t < s["end"]:
            return i, s
    return len(DATA["screens"]) - 1, DATA["screens"][-1]


# ---- slots ------------------------------------------------------------
def sl_headline(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x][:3]
    size = int(o.get("size", 56))
    for j, line in enumerate(lines):
        s = size
        while s > 32 and tw(line, f(s, "bold"), 2) > (RIGHT - CX):
            s -= 3
        L.heading(ov, d, line, t, t0 + j * 0.10, TH,
                  y=int(o.get("y", 420)) + j * int(size * 1.20), size=s)


def _rows(o, key="rows", limit=5):
    out = []
    for row in (o.get(key) or [])[:limit]:
        if isinstance(row, (list, tuple)):
            out.append((str(row[0]), str(row[1]) if len(row) > 1 else None))
        else:
            out.append((str(row), None))
    return out



def _fit_row_value(label, value, avail, lsize, vsize, mono=True):
    """The row draws its label from the left and its value against the right
    edge; nothing else keeps them apart. Trim the value to the room the label
    leaves, ellipsis and all, and drop it entirely when there is no room --
    a missing value reads better than two strings through each other."""
    if not value:
        return value
    room = avail - tw(str(label), f(lsize, "bold"), 1) - 28
    if room < 60:
        return None
    face = (m if mono else f)(vsize)
    out = str(value)
    if tw(out, face, 0) <= room:
        return out
    while out and tw(out + "\\u2026", face, 0) > room:
        out = out[:-1]
    return (out.rstrip() + "\\u2026") if out else None


def sl_factlist(ov, d, t, t0, o, i):
    rows = _rows(o, "rows", int(o.get("rows_limit", 5)))
    y = int(o.get("y", 700))
    for j, (label, value) in enumerate(rows):
        ry = y + j * 88
        value = _fit_row_value(label, value, right_edge(ry) - CX, 34, 28)
        L.row(ov, d, t, t0 + j * 0.09, TH, ry, label, value, h=74)


def sl_tiles(ov, d, t, t0, o, i):
    sl_factlist(ov, d, t, t0, o, i)


def sl_statcards(ov, d, t, t0, o, i):
    stats = [(str(l), str(v)) for v, l in (o.get("stats") or [])][:3]
    y = int(o.get("y", 620))
    for j, (label, value) in enumerate(stats):
        L.row(ov, d, t, t0 + j * 0.11, TH, y + j * 104, label, value,
              lit=1.0, h=88, lsize=36, vsize=32)


def sl_counter(ov, d, t, t0, o, i):
    target = o.get("target")
    if target is None:
        return
    L.counter(ov, d, t, t0, TH, int(o.get("y", 620)), int(target),
              label=str(o.get("label") or "").upper(),
              vsize=int(o.get("size", 128)))


def sl_terminal(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x][:2]
    y = int(o.get("y", 640))
    title = str(o.get("title") or "").strip()
    if title:
        L.heading(ov, d, title, t, t0, TH, y=y - 96, size=46)
    for j, line in enumerate(lines):
        L.stamp(ov, d, t, t0 + 0.10 + j * 0.12, TH, (CX, y + j * 104),
                line, size=30)


def sl_quote(ov, d, t, t0, o, i):
    lines = [x for x in (o.get("lines") or []) if x][:3]
    if lines:
        L.quote(ov, d, t, t0, TH, int(o.get("y", 620)), lines,
                size=int(o.get("size", 40)))


def _panel_band():
    top = 400
    return top, min(1000, (1440 if CAPTIONS else 1560) - top)


def sl_image(ov, d, t, t0, o, i):
    name = o.get("file")
    if not name:
        return
    path = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "images", name)
    img = L.load_scroll(path)
    if img is None:
        return
    top, band = _panel_band()
    k = L.wk(t, t0, 0.36)
    if k <= 0.01:
        return
    show = min(band, img.height)
    crop = img.crop((0, 0, W, show))
    x0 = CX - 22
    L.wipe(ov, lambda Lay, D, c=crop, xx=int(x0), yy=top:
           Lay.paste(c.resize((int(RIGHT - xx), show)), (xx, yy)),
           (x0, top, RIGHT, top + show), k)
    if o.get("label") and top + show + 70 < 1600:
        text(d, (CX, top + show + 28), o["label"], f(40, "bold"), WHITE, k, 0, "lt")


def sl_scroll(ov, d, t, t0, o, i):
    """The repo page, panned inside the stage band under the narration."""
    path = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "images", o.get("file", ""))
    top, band = _panel_band()
    L.scroll(ov, d, t, t0 + 0.30, float(o.get("dur", 8.0)) - 0.30, TH, path,
             y=top, height=band, speed=float(o.get("speed", L.SCROLL_SPEED)),
             label=o.get("label") or "")



# ---- generated clips -------------------------------------------------------
# A clip is a directory of JPEG frames at the reel's own size and frame rate,
# extracted once by the visuals stage, so drawing it is pasting frame n --
# exactly what the repo scroll does with one tall PNG, for the same reason:
# the renderer is a PIL frame pump and cannot decode video.
_CLIP_CACHE = {{}}
_CLIP_ORDER = []


def _clip_frame(dirname, index):
    """One frame, behind a small LRU: a chunk process holds a handful of
    decoded frames rather than a whole clip."""
    key = (dirname, index)
    if key in _CLIP_CACHE:
        return _CLIP_CACHE[key]
    path = os.path.join(_HERE_IMAGES, dirname, "%05d.jpg" % (index + 1))
    try:
        img = Image.open(path).convert("RGBA")
    except Exception:
        img = None
    _CLIP_CACHE[key] = img
    _CLIP_ORDER.append(key)
    while len(_CLIP_ORDER) > 12:
        _CLIP_CACHE.pop(_CLIP_ORDER.pop(0), None)
    return img


def _clip_index(t, t0, fps, n):
    """Ping-pong through the frames, so a scene longer than its clip turns
    around instead of jumping back to the first frame."""
    if n <= 1:
        return 0
    i = int(max(0.0, t - t0) * fps)
    cycle = 2 * (n - 1)
    i %= cycle
    return i if i < n else cycle - i


def _band_scrim(colour, height, solid, fade, flip=False):
    """Solid `colour` for `solid` rows then a fade over `fade` rows -- the
    shape the slab scroll uses so chrome stays legible over a picture."""
    key = ("scrim", tuple(colour), height, solid, fade, flip)
    if key not in _CLIP_CACHE:
        layer = Image.new("RGBA", (W, height), (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        for row in range(height):
            r = height - 1 - row if flip else row
            a = 1.0 if r < solid else max(0.0, 1.0 - (r - solid) / max(1, fade))
            ld.line((0, row, W, row), fill=rgba(colour, a))
        _CLIP_CACHE[key] = layer
    return _CLIP_CACHE[key]

_HERE_IMAGES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "images")


def sl_clip(ov, d, t, t0, o, i):
    """Inside the stage band, hung off the spine like a screenshot: the
    centre of each frame, scaled to the band's width and wiped in."""
    top, band = _panel_band()
    k = L.wk(t, t0, 0.36)
    if k <= 0.01:
        return
    img = _clip_frame(o["dir"], _clip_index(t, t0, int(o.get("fps", 30)), int(o.get("frames", 1))))
    if img is None:
        return
    x0 = CX - 22
    width = int(RIGHT - x0)
    scaled_h = int(img.height * width / img.width)
    show = min(band, scaled_h)
    frame_img = img.convert("RGB").resize((width, scaled_h), Image.LANCZOS)
    y_off = (scaled_h - show) // 2
    crop = frame_img.crop((0, y_off, width, y_off + show))
    L.wipe(ov, lambda Lay, D, c=crop, xx=int(x0), yy=top: Lay.paste(c, (xx, yy)),
           (x0, top, RIGHT, top + show), k)



def _fit_line(value, face, track, budget, url=False):
    """The end cards draw their lines at fixed sizes; the strings bend instead.

    A URL loses its host first -- the path is the identity, the host is
    boilerplate -- and anything still too wide is ellipsis-trimmed. Measured
    with the same face and tracking the card will draw with, because whether
    a line fits depends on which letters it uses."""
    if not value:
        return value
    out = str(value)
    if tw(out, face, track) <= budget:
        return out
    if url and "/" in out:
        out = out.split("/", 1)[1]
        if tw(out, face, track) <= budget:
            return out
    while out and tw(out + "\\u2026", face, track) > budget:
        out = out[:-1]
    return (out.rstrip() + "\\u2026") if out else str(value)[:8]


def sl_endcard(ov, d, t, t0, o, i):
    # L.endcard draws left-aligned from CX at fixed sizes with no fitting of
    # its own; a Hugging Face URL walked straight through the right safe edge
    budget = RIGHT - CX
    L.endcard(ov, d, t, t0 - 0.30, TH, DATA["wordmark"],
              _fit_line(DATA["endcard_sub"], m(34), 2, budget),
              _fit_line(DATA["url"], m(38, "bold"), 0, budget, url=True),
              _fit_line(DATA["url2"], m(30), 0, budget, url=True),
              _fit_line(DATA["cta"], f(34, "bold"), 4, budget - 84),
              mark_size=DATA["mark_size"])


SLOTS = {{
    "headline": sl_headline, "statcards": sl_statcards, "factlist": sl_factlist,
    "terminal": sl_terminal, "tiles": sl_tiles, "counter": sl_counter,
    "quote": sl_quote, "image": sl_image, "scroll": sl_scroll,
    "clip": sl_clip, "endcard": sl_endcard,
}}

PRE_ROLL = 0.30


def frame(t):
    base = BASE.copy()
    ov = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(ov)
    i, screen = screen_at(t)
    t0 = screen["start"] - (PRE_ROLL if screen["start"] > 0.01 else 1.0)
    if screen.get("eyebrow"):
        L.heading(ov, d, screen["eyebrow"], t, t0, TH, y=300, size=34,
                  col=TH.accent, track=5)
    for slot in screen["slots"]:
        SLOTS[slot["kind"]](ov, d, t, t0, slot, i)
    L.chrome(ov, d, t, TH, TOTAL, DATA["tag"], DATA["screens"], i)
    L.advance(ov, d, t, CUTS, TH)
    if CAPTIONS and not screen.get("is_end"):
        L.captions(ov, d, t, CH, TH)
    base.alpha_composite(ov)
    return base


SFX = (
    [{{"t": c - 0.24, "kind": "shift", "amp": 0.10}} for c in CUTS]
    + [{{"t": c, "kind": "latch", "amp": 0.22, "dur": 0.18}} for c in CUTS]
)
'''


#: Which module source and which screen catalogue each family uses. Adding a
#: third is a row here plus a YAML file -- the resolved DATA is shared.
FAMILIES = {
    "bloom": {"template": lambda: TEMPLATE, "catalogue": "default"},
    "slab": {"template": lambda: SLAB_TEMPLATE, "catalogue": "slab"},
    "ledger": {"template": lambda: LEDGER_TEMPLATE, "catalogue": "ledger"},
}


def slab_ramp(theme: dict) -> list[list[int]]:
    """A six-stop field ramp from the content's own palette.

    Slab needs a colour per scene, not one accent, and consecutive fields have
    to differ enough that the wipe reads. Alternating light / dark / saturated
    guarantees that whatever palette the content stage picked.
    """
    accent = list(theme["accent"])
    support = list(theme.get("support") or accent)
    light = [240, 238, 233]
    ink = [max(14, min(28, c)) for c in theme.get("bg", [18, 18, 20])]
    return [light, ink, accent, light, support, ink]


def template_constants() -> dict[str, float]:
    """The constants defined inside TEMPLATE, read back out.

    The safe area and the full-bleed treatments are declared in the emitted
    module, not here -- that is where they are used, and moving them would mean
    two definitions. But the reel-frame preview in the browser needs them, and a
    second copy typed into JavaScript is exactly the drift this avoids. So they
    are parsed from the one place they exist.
    """
    import ast
    import re as _re

    out: dict[str, float] = {}
    for line in TEMPLATE.splitlines():
        match = _re.match(r"^([A-Z][A-Z_, ]*)\s*=\s*(.+)$", line.strip())
        if not match:
            continue
        names = [n.strip() for n in match.group(1).split(",") if n.strip()]
        try:
            value = ast.literal_eval(match.group(2))
        except (ValueError, SyntaxError):
            continue
        values = value if isinstance(value, tuple) else (value,)
        if len(names) != len(values):
            continue
        for name, item in zip(names, values):
            if isinstance(item, (int, float)):
                out[name] = item
    return out


def _clip(text: str, budget: int) -> str:
    """Shorten a string for the screen. See app/text.py for why this is shared."""
    from app.text import trim_to

    return trim_to(text, budget)


def _wrap(text: str, width: int, limit: int) -> list[str]:
    """Break a sentence into at most `limit` lines of about `width` characters."""
    lines: list[str] = []
    current = ""
    for word in str(text).split():
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            lines.append(current)
            current = word
            if len(lines) == limit:
                break
        else:
            current = candidate
    if current and len(lines) < limit:
        lines.append(current)
    return lines[:limit]


def _stat_value(value: str) -> str:
    """Compact a bare count the same way the stat cards and covers do."""
    from app.stages.content import compact_stat

    return compact_stat(str(value))


#: A screen held longer than this stops reading as a cut and starts reading as
#: a slideshow. DEVELOPMENT.md: a cut every 2-4 seconds, and if a layout must hold
#: longer, give it an event every 1-2 seconds inside the hold.
MAX_SCENE_SECONDS = 5.5

#: The smoke check's floor: nothing reads in under this.
MIN_SCENE_SECONDS = 1.2


def scene_spans(segments: list[tuple[float, float]], phrase_scene: list[int],
                total: float, endcard_seconds: float) -> list[tuple[float, float]]:
    """Cut on the narration, not on round numbers.

    Each script scene owns a contiguous run of phrases and ends where its last
    phrase ends, so nothing is left on screen after the line that pays it off.
    A run that would hold past MAX_SCENE_SECONDS is split at the phrase boundary
    nearest that limit, which keeps the rhythm without ever cutting mid-sentence.
    """
    groups, current = [], None
    for phrase_index, scene_index in enumerate(phrase_scene):
        if scene_index != current:
            groups.append([phrase_index])
            current = scene_index
        else:
            groups[-1].append(phrase_index)

    spans, cursor = [], 0.0
    for members in groups:
        run_start = cursor
        for position, phrase_index in enumerate(members):
            # a segment cannot end after the audio does; clamping here keeps
            # every later span arithmetic total-safe
            end = min(segments[min(phrase_index, len(segments) - 1)][1], total)
            if end - run_start >= MAX_SCENE_SECONDS or position == len(members) - 1:
                spans.append((run_start, end))
                run_start = end
        cursor = run_start

    if not spans:
        return [(0.0, total)]

    # Where the end card starts. Preferring `total - endcard_seconds` would cut
    # the last line off when the narration runs long, and preferring the end of
    # the narration gives the end card whatever is left -- which can be nothing,
    # or negative, when the recording has no tail silence. Both ends are
    # clamped: no scene reads in under MIN_SCENE_SECONDS.
    preferred = max(total - endcard_seconds, spans[-1][1] + 0.5)
    earliest = spans[-1][0] + MIN_SCENE_SECONDS
    latest = total - MIN_SCENE_SECONDS
    if earliest <= latest:
        tail = min(max(preferred, earliest), latest)
    else:
        # too short to give both a readable hold; split what there is
        tail = (spans[-1][0] + total) / 2

    spans[-1] = (spans[-1][0], tail)
    spans.append((tail, total))

    # Fewer segments than phrases -- an alignment that never ran, or a caller
    # that forgot to pass one -- makes every group end at the same instant, so
    # every span after the first is zero-length. That renders as a stack of
    # screens nobody sees. An even split is wrong about where the cuts belong
    # but right about there being cuts at all, so it degrades instead of
    # producing a table the smoke check has to reject.
    if any(end - start < MIN_SCENE_SECONDS for start, end in spans):
        count = max(len(spans), 2)
        step = total / count
        spans = [(round(i * step, 3), round((i + 1) * step, 3)) for i in range(count)]
        spans[-1] = (spans[-1][0], total)
    return spans


def _resolve(slot, bundle: dict, variant: int) -> dict | None:
    """Turn a catalogue slot into concrete drawing data, or drop it.

    Returning None is how a layout degrades: a factlist with nothing left to
    show is omitted rather than drawn empty. `variant` slides the window into
    the source list, so a layout that has to appear twice shows the next rows
    rather than the same ones.
    """
    kind, options = slot.kind, dict(slot.options)
    source = options.pop("source", None)
    out = {"kind": kind} | options

    if kind == "endcard":
        return out
    if kind == "headline":
        lines = list(bundle.get(source) or [])
        if not lines:
            return None
        out["lines"] = [_clip(line, 34) for line in lines[:3]]
        # `sub: tagline` names a key in the bundle, not the literal word
        if out.get("sub"):
            out["sub"] = _clip(str(bundle.get(out["sub"], "") or ""), 56) or None
    elif kind == "quote":
        value = bundle.get(source)
        if not value:
            return None
        out["lines"] = _wrap(str(value), 22, 3)
    elif kind == "statcards":
        stats = list(bundle.get(source) or [])
        if not stats:
            return None
        out["stats"] = [[_clip(str(v), 8), _clip(str(l), 11).upper()]
                        for v, l in stats[:3]]
    elif kind == "image":
        pool = list(bundle.get(source) or [])
        if not pool:
            return None
        # variant selects which upload this appearance shows, so three
        # screenshots give three screens rather than the same one three times
        picked = pool[variant % len(pool)]
        fit = picked.get("fit", "panel")
        out["file"] = picked["file"]
        out["fit"] = fit
        out["y"] = 0 if fit == "full" else _panel_y(
            picked.get("height", 600), picked.get("position", "bottom"),
            bundle.get("captions", True))
        # each upload says what it is a picture of, so the screen says it too
        out["eyebrow"] = picked.get("eyebrow", "")
        if picked.get("caption"):
            out["caption"] = _clip(picked["caption"], 44)
        # a generated picture has no text in it by design; the words it
        # needs are painted over it here
        if picked.get("heading"):
            out["label"] = _clip(picked["heading"], 40)
    elif kind == "counter":
        target, label = _countable(bundle, source, variant)
        if target is None:
            return None
        out["target"], out["label"] = target, label
    elif kind == "terminal":
        lines = list(bundle.get(source) or [])
        if not lines:
            return None
        out["lines"] = [_clip(line, 42) for line in lines[:3]]
        out.setdefault("title", bundle.get("command_title", ""))
    elif kind == "scroll":
        shot = bundle.get(source)
        if not shot:
            return None
        out["file"] = shot["file"]
        out["label"] = shot.get("label", "")
    elif kind == "clip":
        pool = list(bundle.get(source) or [])
        if not pool:
            return None
        picked = pool[variant % len(pool)]
        out["dir"] = picked["dir"]
        out["fps"] = int(picked.get("fps", 30))
        out["frames"] = int(picked.get("frames", 1))
        out["label"] = picked.get("label", "")
        out["eyebrow"] = picked.get("label", "")
    elif kind in ("factlist", "tiles"):
        rows = list(bundle.get(source) or [])
        want = int(options.get("rows", 4))
        window = rows[variant * want:(variant + 1) * want] or rows[:want]
        if not window:
            return None
        out["rows"] = [[_clip(str(l), 24), _clip(str(v), 34)] for l, v in window]
    else:
        return None
    return out


#: The band a panel may occupy: below the eyebrow, above the caption band.
#: The band a panel may occupy. The floor depends on whether captions are
#: burned in, because they are drawn over everything else.
#:
#: This used to be a flat 1470, and the burned-in captions start at 1450 -- so
#: *every* bottom-placed panel overlapped them by 20px. The preview built to
#: warn about collisions duly warned about this one on the very first
#: screenshot anyone placed, which is how it was found. With captions off the
#: floor is the safe area instead, because there is nothing there to collide
#: with and a screenshot may as well have the room.
PANEL_TOP = 380
CAPTION_TOP = 1450
PANEL_BOTTOM_CAPTIONED = CAPTION_TOP - 10
PANEL_BOTTOM_BARE = 1580
#: Kept for anything still reading a single floor; the captioned case is the
#: one that constrains.
PANEL_BOTTOM = PANEL_BOTTOM_CAPTIONED


def panel_floor(captions: bool) -> int:
    return PANEL_BOTTOM_CAPTIONED if captions else PANEL_BOTTOM_BARE


def _panel_y(height: int, position: str, captions: bool = True) -> int:
    """Where a panel of this height sits, given where it was asked to sit.

    Bottom is the default because the eyebrow is at the top and a panel placed
    there covers it -- which is what one rendered reel did, with "THE REPO"
    printed across a screenshot.
    """
    floor = panel_floor(captions)
    if position == "top":
        return PANEL_TOP
    if position == "centre":
        return PANEL_TOP + max(0, (floor - PANEL_TOP - height) // 2)
    return max(PANEL_TOP, floor - height)


def _countable(bundle: dict, source: str, variant: int):
    """A stat that is a plain number, so it can tick up rather than appear."""
    candidates = list(bundle.get(source) or [])
    if isinstance(bundle.get(source), (int, float)):
        return int(bundle[source]), None
    # `variant` was accepted and then ignored, so a layout with
    # `repeat_with: stats` counted to the same number every time it appeared.
    # Rotating by the variant makes a repeat show the next countable stat;
    # rotation by 0 is the identity, so the single-appearance case is unchanged.
    if candidates and variant:
        variant %= len(candidates)
        candidates = candidates[variant:] + candidates[:variant]
    for value, label in candidates:
        # stats are compacted for the cards ("38K"), and a counter ticking to
        # 38,000 is the same claim -- so read the compact form back out
        raw = str(value).replace(",", "").rstrip("+").upper()
        scale = {"K": 1_000, "M": 1_000_000, "B": 1_000_000_000}.get(raw[-1:], 1)
        digits = raw[:-1] if scale > 1 else raw
        try:
            return int(float(digits) * scale), str(label).upper()
        except ValueError:
            continue
    return None, None


def build_source(
    content: ReelContent, *, total: float, audio_rel: str, phrases_rel: str,
    endcard_seconds: float = 3.2, captions: bool = True,
    segments: list[tuple[float, float]] | None = None,
    catalogue_name: str | None = None,
    images: list[dict] | None = None,
    family: str = "bloom",
    scroll: dict | None = None,
    clips: list[dict] | None = None,
) -> str:
    """Assemble the module source for this content.

    `family` picks the design language: "bloom" (sbkit) or "slab" (slab.py).
    Both consume the same resolved DATA -- only the emitted module and the
    screen catalogue differ -- so content work is shared between them.
    """
    if family not in FAMILIES:
        raise ValueError(f"unknown storyboard family {family!r}; "
                         f"available: {', '.join(sorted(FAMILIES))}")
    catalogue_name = catalogue_name or FAMILIES[family]["catalogue"]
    facts = [(row.label, _stat_value(row.value)) for row in content.fact_sheet]
    commands = [content.cover.cmd] if content.cover.prompt else []
    if not commands:
        commands = [content.cover.cmd or content.tagline]

    hook_lines = [line for line in content.cover.hook if line.strip()][:3]
    if not hook_lines:
        hook_lines = [content.display_name]

    point_lines = []
    for scene in content.scenes[2:4]:
        first = scene.title.strip()
        if first:
            point_lines.append(_clip(first, 26))
    if not point_lines:
        point_lines = [_clip(content.tagline, 26)]

    bundle = {
        "captions": bool(captions),
        "images": list(images or []),
        "clips": list(clips or []),
        "scroll": dict(scroll) if scroll else None,
        "image_eyebrow": (images[0]["eyebrow"] if images else "A LOOK"),
        "clip_eyebrow": (clips[0].get("label") if clips else "") or "IN MOTION",
        "hook_lines": hook_lines,
        "point_lines": point_lines,
        "stats": [list(x) for x in content.cover.stats],
        "facts": facts,
        "commands": commands,
        "tagline": content.tagline,
        "quote": content.tagline,
        "command_title": content.display_name.lower(),
        "eyebrow": _clip(content.cover.eyebrow, 34).upper(),
        "points_eyebrow": (_clip(content.scenes[2].title, 34).upper()
                           if len(content.scenes) > 2 else "THE INTERESTING PART"),
    }

    spans = scene_spans(
        segments or [(0.0, total)],
        [p.scene_index for p in content.phrases], total, endcard_seconds,
    )
    screens = _build_screens(spans, bundle, catalogue_name)

    data = {
        "captions": bool(captions),
        "screens": screens,
        "theme": {
            "bg": list(content.theme.bg), "accent": list(content.theme.accent),
            "accent_hi": list(content.theme.accent_hi), "pale": list(content.theme.pale),
            "glow": list(content.theme.glow), "support": list(content.theme.support),
            "seed": content.theme.base_seed, "bloom": content.theme.base_bloom,
        },
        "eyebrow": _clip(content.cover.eyebrow, 34).upper(),
        "hook_lines": hook_lines,
        "tagline": _clip(content.tagline, 56),
        "stats": [list(s) for s in content.cover.stats],
        "facts": facts,
        "commands": commands,
        "command_title": content.display_name.lower(),
        "command_eyebrow": "ONE COMMAND" if content.cover.prompt else "WHAT IT GIVES YOU",
        "points_eyebrow": (_clip(content.scenes[2].title, 34).upper()
                           if len(content.scenes) > 2 else "THE INTERESTING PART"),
        "point_lines": point_lines,
        "wordmark": content.cover.wordmark,
        "endcard_sub": _clip(content.tagline, 42),
        "url": content.repo_url.replace("https://", "").replace("http://", ""),
        "url2": content.cover.cmd if content.cover.prompt else "",
        "cta": "SAVE THIS FOR YOUR NEXT SETUP",
        "tag": content.repo_url.rstrip("/").split("/")[-2:] and "/".join(
            content.repo_url.rstrip("/").split("/")[-2:]
        ),
        "endcard_seconds": endcard_seconds,
    }

    if family == "slab":
        data["theme"]["fields"] = slab_ramp(data["theme"])
        data["captions"] = False

    return FAMILIES[family]["template"]().format(
        slug=content.slug, audio=audio_rel, phrases=phrases_rel, total=total,
        # a Python literal, not JSON: the two agree on strings, numbers, lists
        # and dicts, but JSON writes booleans as `true` and this module is
        # executed rather than parsed
        data=pformat(data, indent=4, width=88, sort_dicts=False),
    )


def _build_screens(spans, bundle: dict, catalogue_name: str) -> list[dict]:
    """One resolved screen per span: which layout, which text, at which pixel.

    The last span is always the end card, whatever the catalogue's closer says,
    because `endcard_seconds` already carved that time out of the timeline.
    """
    from app.render.screens import pick

    chosen = pick(len(spans), bundle, catalogue_name)
    screens = []
    for index, ((start, end), (layout, variant)) in enumerate(zip(spans, chosen)):
        slots = [resolved for resolved in
                 (_resolve(slot, bundle, variant) for slot in layout.slots)
                 if resolved]
        is_end = index == len(spans) - 1
        eyebrow = layout.eyebrow
        if eyebrow.startswith("@"):            # pull the text from the content
            eyebrow = str(bundle.get(eyebrow[1:], "") or "")
        # a slot may name its own: three screenshots of different things get
        # three different headings rather than one generic one
        for resolved in slots:
            if resolved.get("eyebrow"):
                eyebrow = resolved["eyebrow"]
                break
        # a scroll paces itself across its own screen, and the span is not
        # knowable at _resolve time -- only here
        for resolved in slots:
            if resolved.get("kind") == "scroll":
                resolved["dur"] = round(end - start, 3)
        screens.append({
            "id": layout.id, "start": round(start, 3), "end": round(end, 3),
            "eyebrow": "" if is_end else eyebrow[:34].upper(),
            "is_end": is_end,
            "slots": slots if not is_end else [{"kind": "endcard"}],
        })
    return screens
